#!/usr/bin/env bash
# install-mac.sh — installs rara-distill as a RESIDENT launchd agent on macOS (distill-mac).
#
# This is the default distillation path (2026-07 decision): the Claude Code CLI's logged-in
# subscription does the curation (CURATE_ENGINE=claude-cli), so there is no per-token API cost
# and no groq free-tier daily cap. Mirrors rara-transcribe/install-local.sh, but resident
# (KeepAlive) instead of calendar-scheduled: the worker polls WORK_POLL_INTERVAL and claims
# destilar item_steps all day while the Mac is on.
#
# Usage: bash install-mac.sh (from the rara-distill/ directory; re-run to update the binary)
set -euo pipefail

INSTALL_DIR="$HOME/.rara-distill"
PLIST_PATH="$HOME/Library/LaunchAgents/com.rara.distill.plist"
LOG_DIR="$HOME/Library/Logs/rara-distill"
LABEL="com.rara.distill"

# ---------------------------------------------------------------------------
# 0. Directory guard — must be run from rara-distill/
# ---------------------------------------------------------------------------
if [ ! -f "go.mod" ] || [ ! -d "patterns" ]; then
    echo "!! Run this script from the rara-distill/ directory:"
    echo "   cd rara-distill && bash install-mac.sh"
    exit 1
fi

# ---------------------------------------------------------------------------
# 1. Prerequisites: go (build) + claude (the engine; must be logged in)
# ---------------------------------------------------------------------------
echo "==> Checking prerequisites..."
missing=()
for cmd in go claude; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        missing+=("$cmd")
    fi
done
if [ ${#missing[@]} -gt 0 ]; then
    echo ""
    echo "!! Missing commands: ${missing[*]}"
    echo "   go:     brew install go"
    echo "   claude: npm install -g @anthropic-ai/claude-code   (then: claude login)"
    exit 1
fi
CLAUDE_REAL=$(command -v claude)
echo "   go:     $(command -v go)"
echo "   claude: $CLAUDE_REAL ($(claude --version 2>/dev/null || echo 'version unknown'))"

# ---------------------------------------------------------------------------
# 2. Create directories
# ---------------------------------------------------------------------------
mkdir -p "$INSTALL_DIR" "$LOG_DIR"

# ---------------------------------------------------------------------------
# 3. Create .env if it does not exist (exits here on first run)
# ---------------------------------------------------------------------------
if [ ! -f "$INSTALL_DIR/.env" ]; then
    echo ""
    echo "==> Creating $INSTALL_DIR/.env..."
    cat > "$INSTALL_DIR/.env" << ENV
# rara-distill (distill-mac) — resident claim-worker on the Claude Code CLI subscription.
# Generated by install-mac.sh; fill in DATABASE_URL, then re-run the installer.

# Neon PostgreSQL (shared contract DB). Use the DIRECT endpoint (host without "-pooler") —
# the pooler drops idle connections mid-LLM-call, and CLI calls take minutes.
DATABASE_URL=postgresql://user:password@ep-xxx.sa-east-1.aws.neon.tech/neondb?sslmode=require

# The engine: local Claude Code CLI, billed to the logged-in subscription (no API key).
CURATE_ENGINE=claude-cli
CLAUDE_MODEL=claude-sonnet-4-6
# Absolute path — launchd has a minimal PATH.
CLAUDE_CLI_BIN=$CLAUDE_REAL

# Worker identity: claims only steps the reconciler routed to distill-mac.
DISTILL_PROVIDER=distill-mac

# Resident: poll the queue on this cadence (also drives the periodic heartbeat).
WORK_POLL_INTERVAL=30s

# Default recipe fallback (per-item recipe comes from flow_steps.options.recipe).
DISTILL_PATTERNS=extract_wisdom
ENV
    echo ""
    echo "!! REQUIRED STEP: edit the file before continuing:"
    echo "   \$EDITOR $INSTALL_DIR/.env"
    echo ""
    echo "   Fill in DATABASE_URL with the real Neon DSN (direct endpoint, not -pooler)."
    echo "   Then run again: bash install-mac.sh"
    exit 0
fi

# ---------------------------------------------------------------------------
# 4. Build the binary (native; the rara-addon replace resolves to ../rara-addon)
# ---------------------------------------------------------------------------
echo ""
echo "==> Building rara-distill..."
go build -ldflags="-w -s" -o "$INSTALL_DIR/distill-job" .
echo "   Binary: $INSTALL_DIR/distill-job"

# ---------------------------------------------------------------------------
# 5. Wrapper script called by launchd
# ---------------------------------------------------------------------------
cat > "$INSTALL_DIR/run.sh" << WRAPPER
#!/bin/bash
# Generated by install-mac.sh — do not edit directly.
# Homebrew/npm bins on PATH: launchd starts with a minimal PATH and the claude CLI needs node.
export PATH="/opt/homebrew/bin:/usr/local/bin:\$HOME/.local/bin:\$PATH"
set -a
source "$INSTALL_DIR/.env"
set +a
exec "$INSTALL_DIR/distill-job" "\$@"
WRAPPER
chmod +x "$INSTALL_DIR/run.sh"

# ---------------------------------------------------------------------------
# 6. Generate and install the launchd plist — RESIDENT (KeepAlive), like
#    com.rara.runner-agent: the worker is a long-lived poller, not a nightly batch.
# ---------------------------------------------------------------------------
mkdir -p "$(dirname "$PLIST_PATH")"
cat > "$PLIST_PATH" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$INSTALL_DIR/run.sh</string>
    </array>

    <!-- Resident worker: relaunch on exit/crash, but never tighter than every 10s. -->
    <key>KeepAlive</key>
    <true/>
    <key>ThrottleInterval</key>
    <integer>10</integer>
    <key>RunAtLoad</key>
    <true/>

    <key>StandardOutPath</key>
    <string>$LOG_DIR/output.log</string>
    <key>StandardErrorPath</key>
    <string>$LOG_DIR/error.log</string>
</dict>
</plist>
PLIST

# ---------------------------------------------------------------------------
# 7. Load (or reload) the launchd agent
# ---------------------------------------------------------------------------
launchctl unload "$PLIST_PATH" 2>/dev/null || true
launchctl load "$PLIST_PATH"

# ---------------------------------------------------------------------------
# 8. Final instructions
# ---------------------------------------------------------------------------
echo ""
echo "✅ rara-distill (distill-mac) installed as a resident launchd agent."
echo ""
echo "   Config:  $INSTALL_DIR/.env"
echo "   Binary:  $INSTALL_DIR/distill-job"
echo "   Logs:    $LOG_DIR/"
echo "   Plist:   $PLIST_PATH"
echo ""
echo "Useful commands:"
echo "  Watch logs (live):   tail -f $LOG_DIR/error.log   # Go logs to stderr"
echo "  Stop service:        launchctl unload $PLIST_PATH"
echo "  Update binary:       cd rara-distill && bash install-mac.sh"
echo ""
echo "Remember: the provider must be enabled for the reconciler to route work here:"
echo "  UPDATE providers SET enabled=true, activation='resident' WHERE name='distill-mac';"
